export let memory = [
  "Hopping down the wood stairs together cause why not!",
  "That first long-but-not-long-enough hug in the light misty sunshower rain",
  "Leaning on the railing with you :p",
  "The best, longest but not long enough hug",
  "Level up hug!",
  "Bumping into you while we walk side by side",
  "Shopping with you and seeing you out in the wild and your food shopping style :p",
  "Running and ramming into you to hug you!",
  "Hiking with you, infront of you, behind you, next to you",
  "Drinking like, 6 different coffee's and a tasty bagel AND nerding out about bread and inside workings of Panera lol",
  "Eating lunch with you!",
  "Sharing all the songs with you",
  "Getting to sit next to you on the boat and just have the best time talking about anything and everything (DOS GAMES)",
  "Stairwell hugs!",
  "My knight in shining armor that gets me the sauce from the way back of the shelf",
  "You asking me which thing (Me over here not knowing the name) to put on the front of your car!",
  "Sitting in complete silence and still being the happiest ever",
  "Sending you meme's while you're RIGHT there just so you can smile",
  "Keeping you posted about the posts!! :p",
];
