export let motivationalQuotes = [
  "Keep going. Because you did not come this far just to come this far.",
  "Forget looking for the next open door and go find a window",
  "Never be a prisoner of your past. It was just a lesson, not a life sentence",
  "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart",
  "Breathe, darling. This is just a chapter. Not your whole story",
  "If you're offered a seat on a rocket ship, don't ask what seat. Just get on",
  "Don't lose the spark that makes you... you",
  "Embrace uncertainty, some of the most beautiful chapters in our lives won't have a title until much later",
  "1 year = 365 opportunities",
  "Because in the end, you won't remember the time you spent working in the office or mowing your lawn. Climb that goddamn mountain",
  "Fall in love with the process of becoming the very best version of yourself",
  "Sometimes what you're most afraid of doing is the very thing that will set you free",
  "Do whatever it takes, with whatever you have",
  "Isn't it funny how day by day nothing seems to change, but when you look back, everything is different...",
  "You only have one life to live, make sure it's yours",
  "You'll never fly with someone else's wings",
  "No one is you, that is one of your superpowers",
  "Be proud of yourself for how hard you're trying",
  "Run the risk. If it works out, happiness. If not, wisdom",
  "Everything's a risk. Not doing anything is a risk. It's up to you",
  "Why else are we here if not to live with unreasonable passion for things",
  "Oh yes, the past can hurt. But from the way I see it, you can either run from it, or learn from it",
  "Remember who you are",
  "Hakuna Matata :p",
  "Your fate lives within you. You only have to be brave enough to see it.",
  "You keep moving forward. Opening new doors, doing new things, because you're curious, and curiousity keeps leading you down new paths",
  "When life gets you down, you know what you've gotta do? Just keep swimming!",
  "Life moves pretty fast. If you don't stop and look around once in a while, you could miss it",
  "You've gotta reach deep down and find the inner wolf inside you",
  "You are much stronger than you think you are. Trust me",
  "The journey is often more important than the destination",
  "In dark places we find outselves. And a little more knowledge lights our way",
  "It's ok to lose: just don't lose the lesson",
  "Patience you must have my young Padawan",
  "One day you will tell your story of how you overcame what you went through, and it will be someone else's survival guide",
  "Rule number 1: Fuck what they think",
  "You can find happiness right where you are",
  "When life throws you a rainy day, play in the puddles",
  "Think of the happiest things. It's the same as having wings",
  "If you cannot do great things, do small things in a great way",
  "Strength is what you gain from the madness you survives",
  "Never be ashamed about being broken, because strength is nothing but pain that's been repaired",
  "There's a crack in everything, that's how the light gets in",
  "Keep going",
  "Always know there are people out there who will always, always believe in you",
  "You're the best thing since sliced bread ( Coming from the baker, that means a lot :p )",
  "I'm pretty sure magic is real, cause here you are",
  "I'm stronger... than this chip!",
  "The moon is a reminder that no matter what phase you're in, you're still whole",
];
