export let you = [
  "Your smile is my favorite time of day",
  "You are my favorite notification!",
  "I love seeing you happy",
  "I miss you! Even tho you're prolly right over there",
  "The way your eyes or even text shines when you talk about being a girl dad",
  "Seeing how focused you look when you're standing up at your desk is great :p",
  "You're one of the strongest people I know",
  "You're amazing! Don't forget that. But don't worry, I won't let you",
  "Watching you drive is like, idk, one of the best things?",
  "The way you lean down to help me at my PC",
  "The way you WALK!",
  "The way you pause for a split second when you're thinking of what to do next",
  "Your eyes when they smile like your mouth when you're happy",
  "The smile you get when you're with Riv is like!! Heart melting! Not to mention how adorable!",
  "You just might be better than coffee...!! Woah!",
  "Pretty sure your laugh is the most contagious thing in the BEST way",
  "You quoting songs I sent, or ones you're listening to! Ahhh. Love seeing the words you like",
];
